package proxy

import "strings"

// cloudflareColoPlaces 把 cf-ray 末尾的机房代码标成城市和国家。
// 来源是公开的 Cloudflare 机房列表，不是网关节点名。未知代码原样显示。
var cloudflareColoPlaces = map[string][2]string{
	"AAE": {"Annabah", "DZ"},
	"ABJ": {"Abidjan", "CI"},
	"ABQ": {"Albuquerque", "US"},
	"ACC": {"Accra", "GH"},
	"ADB": {"Izmir", "TR"},
	"ADD": {"Addis Ababa", "ET"},
	"ADL": {"Adelaide", "AU"},
	"AKL": {"Auckland", "NZ"},
	"AKX": {"Aktyubinsk", "KZ"},
	"ALA": {"Almaty", "KZ"},
	"ALG": {"Algiers", "DZ"},
	"AMD": {"Ahmedabad", "IN"},
	"AMM": {"Amman", "JO"},
	"AMS": {"Amsterdam", "NL"},
	"ANC": {"Anchorage", "US"},
	"ARI": {"Arica", "CL"},
	"ARN": {"Stockholm", "SE"},
	"ARU": {"Aracatuba", "BR"},
	"ASK": {"Yamoussoukro", "CI"},
	"ASU": {"Asuncion", "PY"},
	"ATH": {"Athens", "GR"},
	"ATL": {"Atlanta", "US"},
	"AUS": {"Austin", "US"},
	"BAH": {"Manama", "BH"},
	"BAQ": {"Barranquilla", "CO"},
	"BBI": {"Bhubaneswar", "IN"},
	"BCN": {"Barcelona", "ES"},
	"BDQ": {"Vadodara", "IN"},
	"BEG": {"Belgrad", "RS"},
	"BEL": {"Belem", "BR"},
	"BEY": {"Beirut", "LB"},
	"BGI": {"Bridgetown", "BB"},
	"BGR": {"Bangor", "US"},
	"BGW": {"Baghdad", "IQ"},
	"BKK": {"Bangkok", "TH"},
	"BLR": {"Bangalore", "IN"},
	"BNA": {"Nashville", "US"},
	"BNE": {"Brisbane", "AU"},
	"BOD": {"Bordeaux/Merignac", "FR"},
	"BOG": {"Bogota", "CO"},
	"BOM": {"Mumbai", "IN"},
	"BOS": {"Boston", "US"},
	"BRU": {"Brussels", "BE"},
	"BSB": {"Brasilia", "BR"},
	"BSR": {"Basrah", "IQ"},
	"BTS": {"Bratislava", "SK"},
	"BUD": {"Budapest", "HU"},
	"BUF": {"Buffalo", "US"},
	"BWN": {"Bandar Seri Begawan", "BN"},
	"CAI": {"Cairo", "EG"},
	"CAW": {"Campos Dos Goytacazes", "BR"},
	"CBR": {"Canberra", "AU"},
	"CCU": {"Kolkata", "IN"},
	"CDG": {"Paris", "FR"},
	"CEB": {"Lapu-Lapu City", "PH"},
	"CFC": {"Caçador", "BR"},
	"CGB": {"Cuiaba", "BR"},
	"CGK": {"Jakarta", "ID"},
	"CGP": {"Chittagong", "BD"},
	"CGY": {"Cagayan De Oro City", "PH"},
	"CHC": {"Christchurch", "NZ"},
	"CJB": {"Coimbatore", "IN"},
	"CLE": {"Cleveland", "US"},
	"CLO": {"Cali", "CO"},
	"CLT": {"Charlotte", "US"},
	"CMB": {"Colombo", "LK"},
	"CMH": {"Columbus", "US"},
	"CNF": {"Belo Horizonte", "BR"},
	"CNN": {"Mattanur", "IN"},
	"CNX": {"Chiang Mai", "TH"},
	"COK": {"Cochin", "IN"},
	"COR": {"Cordoba", "AR"},
	"CPH": {"Copenhagen", "DK"},
	"CPT": {"Cape Town", "ZA"},
	"CRK": {"Mabalacat", "PH"},
	"CVG": {"Hebron", "US"},
	"CWB": {"Curitiba", "BR"},
	"CZL": {"Constantine", "DZ"},
	"DAC": {"Dhaka", "BD"},
	"DAD": {"Da Nang", "VN"},
	"DAR": {"Dar es Salaam", "TZ"},
	"DEL": {"New Delhi", "IN"},
	"DEN": {"Denver", "US"},
	"DFW": {"Dallas-Fort Worth", "US"},
	"DKR": {"Dakar", "SN"},
	"DLA": {"Douala", "CM"},
	"DME": {"Moscow", "RU"},
	"DMM": {"Ad Dammam", "SA"},
	"DOH": {"Doha", "QA"},
	"DPS": {"Denpasar-Bali Island", "ID"},
	"DTW": {"Detroit", "US"},
	"DUB": {"Dublin", "IE"},
	"DUR": {"Durban", "ZA"},
	"DUS": {"Dusseldorf", "DE"},
	"DXB": {"Dubai", "AE"},
	"DYU": {"Dushanbe", "TJ"},
	"EBB": {"Kampala", "UG"},
	"EBL": {"Arbil", "IQ"},
	"EVN": {"Yerevan", "AM"},
	"EWR": {"Newark", "US"},
	"EZE": {"Ezeiza", "AR"},
	"FCO": {"Rome", "IT"},
	"FIH": {"Kinshasa", "CD"},
	"FLN": {"Florianopolis", "BR"},
	"FOR": {"Fortaleza", "BR"},
	"FRA": {"Frankfurt-am-Main", "DE"},
	"FRU": {"Bishkek", "KG"},
	"FSD": {"Sioux Falls", "US"},
	"FUK": {"Fukuoka", "JP"},
	"GBE": {"Gaborone", "BW"},
	"GDL": {"Guadalajara", "MX"},
	"GEO": {"Georgetown", "GY"},
	"GIG": {"Rio De Janeiro", "BR"},
	"GND": {"Saint George's", "GD"},
	"GOT": {"Gothenburg", "SE"},
	"GRU": {"Sao Paulo", "BR"},
	"GUA": {"Guatemala City", "GT"},
	"GUM": {"Hagatna", "GU"},
	"GVA": {"Geneva", "CH"},
	"GYD": {"Baku", "AZ"},
	"GYE": {"Guayaquil", "EC"},
	"GYN": {"Goiania", "BR"},
	"HAM": {"Hamburg", "DE"},
	"HAN": {"Hanoi", "VN"},
	"HBA": {"Hobart", "AU"},
	"HEL": {"Helsinki", "FI"},
	"HFA": {"Haifa", "IL"},
	"HKG": {"Hong Kong", "HK"},
	"HNL": {"Honolulu", "US"},
	"HRE": {"Harare", "ZW"},
	"HYD": {"Hyderabad", "IN"},
	"IAD": {"Dulles", "US"},
	"IAH": {"Houston", "US"},
	"ICN": {"Seoul", "KR"},
	"IND": {"Indianapolis", "US"},
	"ISB": {"Islamabad", "PK"},
	"IST": {"Arnavutkoy", "TR"},
	"ISU": {"Sulaymaniyah", "IQ"},
	"IXC": {"Chandigarh", "IN"},
	"JAX": {"Jacksonville", "US"},
	"JDO": {"Juazeiro Do Norte", "BR"},
	"JED": {"Jeddah", "SA"},
	"JHB": {"Senai", "MY"},
	"JIB": {"Djibouti City", "DJ"},
	"JNB": {"Johannesburg", "ZA"},
	"JOG": {"Yogyakarta-Java Island", "ID"},
	"JOI": {"Joinville", "BR"},
	"JRG": {"Jharsuguda", "IN"},
	"KBP": {"Kiev", "UA"},
	"KCH": {"Kuching", "MY"},
	"KEF": {"Reykjavik", "IS"},
	"KGL": {"Kigali", "RW"},
	"KHH": {"Kaohsiung City", "TW"},
	"KHI": {"Karachi", "PK"},
	"KIN": {"Kingston", "JM"},
	"KIX": {"Osaka", "JP"},
	"KNU": {"Kanpur", "IN"},
	"KTM": {"Kathmandu", "NP"},
	"KUL": {"Kuala Lumpur", "MY"},
	"KWI": {"Kuwait City", "KW"},
	"LAD": {"Luanda", "AO"},
	"LAS": {"Las Vegas", "US"},
	"LAX": {"Los Angeles", "US"},
	"LCA": {"Larnarca", "CY"},
	"LED": {"St. Petersburg", "RU"},
	"LHE": {"Lahore", "PK"},
	"LHR": {"London", "GB"},
	"LIM": {"Lima", "PE"},
	"LIS": {"Lisbon", "PT"},
	"LJU": {"Ljubljana", "SI"},
	"LLK": {"Lankaran", "AZ"},
	"LLW": {"Lilongwe", "MW"},
	"LOS": {"Lagos", "NG"},
	"LPB": {"La Paz / El Alto", "BO"},
	"LUN": {"Lusaka", "ZM"},
	"LUX": {"Luxembourg", "LU"},
	"LYS": {"Lyon", "FR"},
	"MAA": {"Chennai", "IN"},
	"MAD": {"Madrid", "ES"},
	"MAN": {"Manchester", "GB"},
	"MAO": {"Manaus", "BR"},
	"MBA": {"Mombasa", "KE"},
	"MCI": {"Kansas City", "US"},
	"MCT": {"Muscat", "OM"},
	"MDE": {"Rionegro", "CO"},
	"MEL": {"Melbourne", "AU"},
	"MEM": {"Memphis", "US"},
	"MEX": {"Mexico City", "MX"},
	"MFM": {"Taipa", "MO"},
	"MIA": {"Miami", "US"},
	"MLA": {"Luqa", "MT"},
	"MLE": {"Male", "MV"},
	"MLG": {"Malang-Java Island", "ID"},
	"MNL": {"Manila", "PH"},
	"MPM": {"Maputo", "MZ"},
	"MRS": {"Marseille", "FR"},
	"MRU": {"Port Louis", "MU"},
	"MSP": {"Minneapolis", "US"},
	"MSQ": {"Minsk", "BY"},
	"MUC": {"Munich", "DE"},
	"MXP": {"Milan", "IT"},
	"NAG": {"Naqpur", "IN"},
	"NBO": {"Nairobi", "KE"},
	"NJF": {"Najaf", "IQ"},
	"NOU": {"Noumea", "NC"},
	"NQN": {"Neuquen", "AR"},
	"NQZ": {"Astana", "KZ"},
	"NRT": {"Tokyo", "JP"},
	"NVT": {"Navegantes", "BR"},
	"OKA": {"Naha", "JP"},
	"OKC": {"Oklahoma City", "US"},
	"OMA": {"Omaha", "US"},
	"ORD": {"Chicago", "US"},
	"ORF": {"Norfolk", "US"},
	"ORN": {"Oran", "DZ"},
	"OSL": {"Oslo", "NO"},
	"OTP": {"Bucharest", "RO"},
	"OUA": {"Ouagadougou", "BF"},
	"PAT": {"Patna", "IN"},
	"PBH": {"Paro", "BT"},
	"PBM": {"Zandery", "SR"},
	"PDX": {"Portland", "US"},
	"PER": {"Perth", "AU"},
	"PHL": {"Philadelphia", "US"},
	"PHX": {"Phoenix", "US"},
	"PIT": {"Pittsburgh", "US"},
	"PMO": {"Palermo", "IT"},
	"PMW": {"Palmas", "BR"},
	"PNH": {"Phnom Penh", "KH"},
	"PNQ": {"Pune", "IN"},
	"POA": {"Porto Alegre", "BR"},
	"POS": {"Port of Spain", "TT"},
	"PPT": {"Papeete", "PF"},
	"PRG": {"Prague", "CZ"},
	"PTY": {"Tocumen", "PA"},
	"QRO": {"Queretaro", "MX"},
	"QWJ": {"Americana", "BR"},
	"RAO": {"Ribeirao Preto", "BR"},
	"RDU": {"Raleigh/Durham", "US"},
	"REC": {"Recife", "BR"},
	"RIC": {"Richmond", "US"},
	"RIX": {"Riga", "LV"},
	"RUH": {"Riyadh", "SA"},
	"RUN": {"St Denis", "RE"},
	"SAN": {"San Diego", "US"},
	"SAP": {"La Mesa", "HN"},
	"SAT": {"San Antonio", "US"},
	"SCL": {"Santiago", "CL"},
	"SDQ": {"Santo Domingo", "DO"},
	"SEA": {"Seattle", "US"},
	"SFO": {"San Francisco", "US"},
	"SGN": {"Ho Chi Minh City", "VN"},
	"SIN": {"Singapore", "SG"},
	"SJC": {"San Jose", "US"},
	"SJK": {"Sao Jose Dos Campos", "BR"},
	"SJO": {"San Jose", "CR"},
	"SJP": {"Sao Jose Do Rio Preto", "BR"},
	"SJU": {"San Juan", "PR"},
	"SKG": {"Thessaloniki", "GR"},
	"SKP": {"Skopje", "MK"},
	"SLC": {"Salt Lake City", "US"},
	"SMF": {"Sacramento", "US"},
	"SOD": {"Sorocaba", "BR"},
	"SOF": {"Sofia", "BG"},
	"SSA": {"Salvador", "BR"},
	"STI": {"Santiago", "DO"},
	"STL": {"St Louis", "US"},
	"STR": {"Stuttgart", "DE"},
	"SUV": {"Nausori", "FJ"},
	"SYD": {"Sydney", "AU"},
	"TBS": {"Tbilisi", "GE"},
	"TGU": {"Tegucigalpa", "HN"},
	"TIA": {"Tirana", "AL"},
	"TLH": {"Tallahassee", "US"},
	"TLL": {"Tallinn", "EE"},
	"TLV": {"Tel Aviv", "IL"},
	"TNR": {"Antananarivo", "MG"},
	"TPA": {"Tampa", "US"},
	"TPE": {"Taipei", "TW"},
	"TUN": {"Tunis", "TN"},
	"TXL": {"Berlin", "DE"},
	"UDI": {"Uberlandia", "BR"},
	"UDR": {"Udaipur", "IN"},
	"UIO": {"Quito", "EC"},
	"ULN": {"Ulan Bator", "MN"},
	"URT": {"Surat Thani", "TH"},
	"VCP": {"Campinas", "BR"},
	"VIE": {"Vienna", "AT"},
	"VIX": {"Vitoria", "BR"},
	"VNO": {"Vilnius", "LT"},
	"VTE": {"Vientiane", "LA"},
	"WAW": {"Warsaw", "PL"},
	"WDH": {"Windhoek", "NA"},
	"WLG": {"Wellington", "NZ"},
	"WRO": {"Wroclaw", "PL"},
	"XAP": {"Chapeco", "BR"},
	"XNH": {"Nasiriyah", "IQ"},
	"YHZ": {"Halifax", "CA"},
	"YUL": {"Montreal", "CA"},
	"YVR": {"Vancouver", "CA"},
	"YWG": {"Winnipeg", "CA"},
	"YXE": {"Saskatoon", "CA"},
	"YYC": {"Calgary", "CA"},
	"YYZ": {"Toronto", "CA"},
	"ZAG": {"Zagreb", "HR"},
	"ZDM": {"Ramallah", "PS"},
	"ZRH": {"Zurich", "CH"},
}

func cloudflareColoPlace(code string) (city, country string, ok bool) {
	place, ok := cloudflareColoPlaces[code]
	if !ok {
		return "", "", false
	}
	return place[0], place[1], true
}

// cloudflareRayColo 取 cf-ray 末尾的机房代码。格式是 16 位十六进制加三个字母。
func cloudflareRayColo(ray string) string {
	ray = strings.TrimSpace(ray)
	dash := strings.LastIndex(ray, "-")
	if dash < 0 || dash == len(ray)-1 {
		return ""
	}
	code := ray[dash+1:]
	if len(code) != 3 {
		return ""
	}
	for _, r := range code {
		if r < 'A' || r > 'Z' {
			return ""
		}
	}
	id := ray[:dash]
	if len(id) != 16 {
		return ""
	}
	for _, r := range id {
		switch {
		case r >= '0' && r <= '9', r >= 'a' && r <= 'f', r >= 'A' && r <= 'F':
		default:
			return ""
		}
	}
	return code
}
