export type EdgePlace = { city: string; country: string }

// Cloudflare 机房代码到城市。cf-ray 末尾三位就是这个代码。
export const cloudflareColos: Record<string, EdgePlace> = {
  AAE: { city: "Annabah", country: "DZ" },
  ABJ: { city: "Abidjan", country: "CI" },
  ABQ: { city: "Albuquerque", country: "US" },
  ACC: { city: "Accra", country: "GH" },
  ADB: { city: "Izmir", country: "TR" },
  ADD: { city: "Addis Ababa", country: "ET" },
  ADL: { city: "Adelaide", country: "AU" },
  AKL: { city: "Auckland", country: "NZ" },
  AKX: { city: "Aktyubinsk", country: "KZ" },
  ALA: { city: "Almaty", country: "KZ" },
  ALG: { city: "Algiers", country: "DZ" },
  AMD: { city: "Ahmedabad", country: "IN" },
  AMM: { city: "Amman", country: "JO" },
  AMS: { city: "Amsterdam", country: "NL" },
  ANC: { city: "Anchorage", country: "US" },
  ARI: { city: "Arica", country: "CL" },
  ARN: { city: "Stockholm", country: "SE" },
  ARU: { city: "Aracatuba", country: "BR" },
  ASK: { city: "Yamoussoukro", country: "CI" },
  ASU: { city: "Asuncion", country: "PY" },
  ATH: { city: "Athens", country: "GR" },
  ATL: { city: "Atlanta", country: "US" },
  AUS: { city: "Austin", country: "US" },
  BAH: { city: "Manama", country: "BH" },
  BAQ: { city: "Barranquilla", country: "CO" },
  BBI: { city: "Bhubaneswar", country: "IN" },
  BCN: { city: "Barcelona", country: "ES" },
  BDQ: { city: "Vadodara", country: "IN" },
  BEG: { city: "Belgrad", country: "RS" },
  BEL: { city: "Belem", country: "BR" },
  BEY: { city: "Beirut", country: "LB" },
  BGI: { city: "Bridgetown", country: "BB" },
  BGR: { city: "Bangor", country: "US" },
  BGW: { city: "Baghdad", country: "IQ" },
  BKK: { city: "Bangkok", country: "TH" },
  BLR: { city: "Bangalore", country: "IN" },
  BNA: { city: "Nashville", country: "US" },
  BNE: { city: "Brisbane", country: "AU" },
  BOD: { city: "Bordeaux/Merignac", country: "FR" },
  BOG: { city: "Bogota", country: "CO" },
  BOM: { city: "Mumbai", country: "IN" },
  BOS: { city: "Boston", country: "US" },
  BRU: { city: "Brussels", country: "BE" },
  BSB: { city: "Brasilia", country: "BR" },
  BSR: { city: "Basrah", country: "IQ" },
  BTS: { city: "Bratislava", country: "SK" },
  BUD: { city: "Budapest", country: "HU" },
  BUF: { city: "Buffalo", country: "US" },
  BWN: { city: "Bandar Seri Begawan", country: "BN" },
  CAI: { city: "Cairo", country: "EG" },
  CAW: { city: "Campos Dos Goytacazes", country: "BR" },
  CBR: { city: "Canberra", country: "AU" },
  CCU: { city: "Kolkata", country: "IN" },
  CDG: { city: "Paris", country: "FR" },
  CEB: { city: "Lapu-Lapu City", country: "PH" },
  CFC: { city: "Caçador", country: "BR" },
  CGB: { city: "Cuiaba", country: "BR" },
  CGK: { city: "Jakarta", country: "ID" },
  CGP: { city: "Chittagong", country: "BD" },
  CGY: { city: "Cagayan De Oro City", country: "PH" },
  CHC: { city: "Christchurch", country: "NZ" },
  CJB: { city: "Coimbatore", country: "IN" },
  CLE: { city: "Cleveland", country: "US" },
  CLO: { city: "Cali", country: "CO" },
  CLT: { city: "Charlotte", country: "US" },
  CMB: { city: "Colombo", country: "LK" },
  CMH: { city: "Columbus", country: "US" },
  CNF: { city: "Belo Horizonte", country: "BR" },
  CNN: { city: "Mattanur", country: "IN" },
  CNX: { city: "Chiang Mai", country: "TH" },
  COK: { city: "Cochin", country: "IN" },
  COR: { city: "Cordoba", country: "AR" },
  CPH: { city: "Copenhagen", country: "DK" },
  CPT: { city: "Cape Town", country: "ZA" },
  CRK: { city: "Mabalacat", country: "PH" },
  CVG: { city: "Hebron", country: "US" },
  CWB: { city: "Curitiba", country: "BR" },
  CZL: { city: "Constantine", country: "DZ" },
  DAC: { city: "Dhaka", country: "BD" },
  DAD: { city: "Da Nang", country: "VN" },
  DAR: { city: "Dar es Salaam", country: "TZ" },
  DEL: { city: "New Delhi", country: "IN" },
  DEN: { city: "Denver", country: "US" },
  DFW: { city: "Dallas-Fort Worth", country: "US" },
  DKR: { city: "Dakar", country: "SN" },
  DLA: { city: "Douala", country: "CM" },
  DME: { city: "Moscow", country: "RU" },
  DMM: { city: "Ad Dammam", country: "SA" },
  DOH: { city: "Doha", country: "QA" },
  DPS: { city: "Denpasar-Bali Island", country: "ID" },
  DTW: { city: "Detroit", country: "US" },
  DUB: { city: "Dublin", country: "IE" },
  DUR: { city: "Durban", country: "ZA" },
  DUS: { city: "Dusseldorf", country: "DE" },
  DXB: { city: "Dubai", country: "AE" },
  DYU: { city: "Dushanbe", country: "TJ" },
  EBB: { city: "Kampala", country: "UG" },
  EBL: { city: "Arbil", country: "IQ" },
  EVN: { city: "Yerevan", country: "AM" },
  EWR: { city: "Newark", country: "US" },
  EZE: { city: "Ezeiza", country: "AR" },
  FCO: { city: "Rome", country: "IT" },
  FIH: { city: "Kinshasa", country: "CD" },
  FLN: { city: "Florianopolis", country: "BR" },
  FOR: { city: "Fortaleza", country: "BR" },
  FRA: { city: "Frankfurt-am-Main", country: "DE" },
  FRU: { city: "Bishkek", country: "KG" },
  FSD: { city: "Sioux Falls", country: "US" },
  FUK: { city: "Fukuoka", country: "JP" },
  GBE: { city: "Gaborone", country: "BW" },
  GDL: { city: "Guadalajara", country: "MX" },
  GEO: { city: "Georgetown", country: "GY" },
  GIG: { city: "Rio De Janeiro", country: "BR" },
  GND: { city: "Saint George's", country: "GD" },
  GOT: { city: "Gothenburg", country: "SE" },
  GRU: { city: "Sao Paulo", country: "BR" },
  GUA: { city: "Guatemala City", country: "GT" },
  GUM: { city: "Hagatna", country: "GU" },
  GVA: { city: "Geneva", country: "CH" },
  GYD: { city: "Baku", country: "AZ" },
  GYE: { city: "Guayaquil", country: "EC" },
  GYN: { city: "Goiania", country: "BR" },
  HAM: { city: "Hamburg", country: "DE" },
  HAN: { city: "Hanoi", country: "VN" },
  HBA: { city: "Hobart", country: "AU" },
  HEL: { city: "Helsinki", country: "FI" },
  HFA: { city: "Haifa", country: "IL" },
  HKG: { city: "Hong Kong", country: "HK" },
  HNL: { city: "Honolulu", country: "US" },
  HRE: { city: "Harare", country: "ZW" },
  HYD: { city: "Hyderabad", country: "IN" },
  IAD: { city: "Dulles", country: "US" },
  IAH: { city: "Houston", country: "US" },
  ICN: { city: "Seoul", country: "KR" },
  IND: { city: "Indianapolis", country: "US" },
  ISB: { city: "Islamabad", country: "PK" },
  IST: { city: "Arnavutkoy", country: "TR" },
  ISU: { city: "Sulaymaniyah", country: "IQ" },
  IXC: { city: "Chandigarh", country: "IN" },
  JAX: { city: "Jacksonville", country: "US" },
  JDO: { city: "Juazeiro Do Norte", country: "BR" },
  JED: { city: "Jeddah", country: "SA" },
  JHB: { city: "Senai", country: "MY" },
  JIB: { city: "Djibouti City", country: "DJ" },
  JNB: { city: "Johannesburg", country: "ZA" },
  JOG: { city: "Yogyakarta-Java Island", country: "ID" },
  JOI: { city: "Joinville", country: "BR" },
  JRG: { city: "Jharsuguda", country: "IN" },
  KBP: { city: "Kiev", country: "UA" },
  KCH: { city: "Kuching", country: "MY" },
  KEF: { city: "Reykjavik", country: "IS" },
  KGL: { city: "Kigali", country: "RW" },
  KHH: { city: "Kaohsiung City", country: "TW" },
  KHI: { city: "Karachi", country: "PK" },
  KIN: { city: "Kingston", country: "JM" },
  KIX: { city: "Osaka", country: "JP" },
  KNU: { city: "Kanpur", country: "IN" },
  KTM: { city: "Kathmandu", country: "NP" },
  KUL: { city: "Kuala Lumpur", country: "MY" },
  KWI: { city: "Kuwait City", country: "KW" },
  LAD: { city: "Luanda", country: "AO" },
  LAS: { city: "Las Vegas", country: "US" },
  LAX: { city: "Los Angeles", country: "US" },
  LCA: { city: "Larnarca", country: "CY" },
  LED: { city: "St. Petersburg", country: "RU" },
  LHE: { city: "Lahore", country: "PK" },
  LHR: { city: "London", country: "GB" },
  LIM: { city: "Lima", country: "PE" },
  LIS: { city: "Lisbon", country: "PT" },
  LJU: { city: "Ljubljana", country: "SI" },
  LLK: { city: "Lankaran", country: "AZ" },
  LLW: { city: "Lilongwe", country: "MW" },
  LOS: { city: "Lagos", country: "NG" },
  LPB: { city: "La Paz / El Alto", country: "BO" },
  LUN: { city: "Lusaka", country: "ZM" },
  LUX: { city: "Luxembourg", country: "LU" },
  LYS: { city: "Lyon", country: "FR" },
  MAA: { city: "Chennai", country: "IN" },
  MAD: { city: "Madrid", country: "ES" },
  MAN: { city: "Manchester", country: "GB" },
  MAO: { city: "Manaus", country: "BR" },
  MBA: { city: "Mombasa", country: "KE" },
  MCI: { city: "Kansas City", country: "US" },
  MCT: { city: "Muscat", country: "OM" },
  MDE: { city: "Rionegro", country: "CO" },
  MEL: { city: "Melbourne", country: "AU" },
  MEM: { city: "Memphis", country: "US" },
  MEX: { city: "Mexico City", country: "MX" },
  MFM: { city: "Taipa", country: "MO" },
  MIA: { city: "Miami", country: "US" },
  MLA: { city: "Luqa", country: "MT" },
  MLE: { city: "Male", country: "MV" },
  MLG: { city: "Malang-Java Island", country: "ID" },
  MNL: { city: "Manila", country: "PH" },
  MPM: { city: "Maputo", country: "MZ" },
  MRS: { city: "Marseille", country: "FR" },
  MRU: { city: "Port Louis", country: "MU" },
  MSP: { city: "Minneapolis", country: "US" },
  MSQ: { city: "Minsk", country: "BY" },
  MUC: { city: "Munich", country: "DE" },
  MXP: { city: "Milan", country: "IT" },
  NAG: { city: "Naqpur", country: "IN" },
  NBO: { city: "Nairobi", country: "KE" },
  NJF: { city: "Najaf", country: "IQ" },
  NOU: { city: "Noumea", country: "NC" },
  NQN: { city: "Neuquen", country: "AR" },
  NQZ: { city: "Astana", country: "KZ" },
  NRT: { city: "Tokyo", country: "JP" },
  NVT: { city: "Navegantes", country: "BR" },
  OKA: { city: "Naha", country: "JP" },
  OKC: { city: "Oklahoma City", country: "US" },
  OMA: { city: "Omaha", country: "US" },
  ORD: { city: "Chicago", country: "US" },
  ORF: { city: "Norfolk", country: "US" },
  ORN: { city: "Oran", country: "DZ" },
  OSL: { city: "Oslo", country: "NO" },
  OTP: { city: "Bucharest", country: "RO" },
  OUA: { city: "Ouagadougou", country: "BF" },
  PAT: { city: "Patna", country: "IN" },
  PBH: { city: "Paro", country: "BT" },
  PBM: { city: "Zandery", country: "SR" },
  PDX: { city: "Portland", country: "US" },
  PER: { city: "Perth", country: "AU" },
  PHL: { city: "Philadelphia", country: "US" },
  PHX: { city: "Phoenix", country: "US" },
  PIT: { city: "Pittsburgh", country: "US" },
  PMO: { city: "Palermo", country: "IT" },
  PMW: { city: "Palmas", country: "BR" },
  PNH: { city: "Phnom Penh", country: "KH" },
  PNQ: { city: "Pune", country: "IN" },
  POA: { city: "Porto Alegre", country: "BR" },
  POS: { city: "Port of Spain", country: "TT" },
  PPT: { city: "Papeete", country: "PF" },
  PRG: { city: "Prague", country: "CZ" },
  PTY: { city: "Tocumen", country: "PA" },
  QRO: { city: "Queretaro", country: "MX" },
  QWJ: { city: "Americana", country: "BR" },
  RAO: { city: "Ribeirao Preto", country: "BR" },
  RDU: { city: "Raleigh/Durham", country: "US" },
  REC: { city: "Recife", country: "BR" },
  RIC: { city: "Richmond", country: "US" },
  RIX: { city: "Riga", country: "LV" },
  RUH: { city: "Riyadh", country: "SA" },
  RUN: { city: "St Denis", country: "RE" },
  SAN: { city: "San Diego", country: "US" },
  SAP: { city: "La Mesa", country: "HN" },
  SAT: { city: "San Antonio", country: "US" },
  SCL: { city: "Santiago", country: "CL" },
  SDQ: { city: "Santo Domingo", country: "DO" },
  SEA: { city: "Seattle", country: "US" },
  SFO: { city: "San Francisco", country: "US" },
  SGN: { city: "Ho Chi Minh City", country: "VN" },
  SIN: { city: "Singapore", country: "SG" },
  SJC: { city: "San Jose", country: "US" },
  SJK: { city: "Sao Jose Dos Campos", country: "BR" },
  SJO: { city: "San Jose", country: "CR" },
  SJP: { city: "Sao Jose Do Rio Preto", country: "BR" },
  SJU: { city: "San Juan", country: "PR" },
  SKG: { city: "Thessaloniki", country: "GR" },
  SKP: { city: "Skopje", country: "MK" },
  SLC: { city: "Salt Lake City", country: "US" },
  SMF: { city: "Sacramento", country: "US" },
  SOD: { city: "Sorocaba", country: "BR" },
  SOF: { city: "Sofia", country: "BG" },
  SSA: { city: "Salvador", country: "BR" },
  STI: { city: "Santiago", country: "DO" },
  STL: { city: "St Louis", country: "US" },
  STR: { city: "Stuttgart", country: "DE" },
  SUV: { city: "Nausori", country: "FJ" },
  SYD: { city: "Sydney", country: "AU" },
  TBS: { city: "Tbilisi", country: "GE" },
  TGU: { city: "Tegucigalpa", country: "HN" },
  TIA: { city: "Tirana", country: "AL" },
  TLH: { city: "Tallahassee", country: "US" },
  TLL: { city: "Tallinn", country: "EE" },
  TLV: { city: "Tel Aviv", country: "IL" },
  TNR: { city: "Antananarivo", country: "MG" },
  TPA: { city: "Tampa", country: "US" },
  TPE: { city: "Taipei", country: "TW" },
  TUN: { city: "Tunis", country: "TN" },
  TXL: { city: "Berlin", country: "DE" },
  UDI: { city: "Uberlandia", country: "BR" },
  UDR: { city: "Udaipur", country: "IN" },
  UIO: { city: "Quito", country: "EC" },
  ULN: { city: "Ulan Bator", country: "MN" },
  URT: { city: "Surat Thani", country: "TH" },
  VCP: { city: "Campinas", country: "BR" },
  VIE: { city: "Vienna", country: "AT" },
  VIX: { city: "Vitoria", country: "BR" },
  VNO: { city: "Vilnius", country: "LT" },
  VTE: { city: "Vientiane", country: "LA" },
  WAW: { city: "Warsaw", country: "PL" },
  WDH: { city: "Windhoek", country: "NA" },
  WLG: { city: "Wellington", country: "NZ" },
  WRO: { city: "Wroclaw", country: "PL" },
  XAP: { city: "Chapeco", country: "BR" },
  XNH: { city: "Nasiriyah", country: "IQ" },
  YHZ: { city: "Halifax", country: "CA" },
  YUL: { city: "Montreal", country: "CA" },
  YVR: { city: "Vancouver", country: "CA" },
  YWG: { city: "Winnipeg", country: "CA" },
  YXE: { city: "Saskatoon", country: "CA" },
  YYC: { city: "Calgary", country: "CA" },
  YYZ: { city: "Toronto", country: "CA" },
  ZAG: { city: "Zagreb", country: "HR" },
  ZDM: { city: "Ramallah", country: "PS" },
  ZRH: { city: "Zurich", country: "CH" },
}
